name: "Kubernetes Canary Release with Rollback"

on:
  workflow_dispatch: # Manually triggered for flexibility

jobs:
  canary-deployment:
    runs-on: ubuntu-latest
    environment: canary
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Kubeconfig
        run: |
          echo "${{ secrets.KUBECONFIG }}" > ./kubernetes-config

      - name: Setup kubectl
        uses: azure/setup-kubectl@v4
      
      - run: ls -la

      - name: Deploy Stable to Kubernetes
        run: |
          kubectl apply -f deployment.yml --kubeconfig=$KUBECONFIG
          kubectl apply -f ingress.yml --kubeconfig=$KUBECONFIG

      - name: Deploy Canary to Kubernetes
        run: |
          kubectl apply -f deployment-canary.yml --kubeconfig=$KUBECONFIG
          kubectl apply -f ingress-canary.yml --kubeconfig=$KUBECONFIG

  canary-10-percent:
    runs-on: ubuntu-latest
    environment:
      name: canary-10
      url: https://6b4407.learnk8s.jamesisme.com # Your canary environment URL
    needs: canary-deployment
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Kubeconfig
        run: |
          echo "${{ secrets.KUBECONFIG }}" > ./kubernetes-config

      - name: Setup kubectl
        uses: azure/setup-kubectl@v4

      - name: Set Canary to 10% Traffic
        run: |
          kubectl annotate ingress myapp-canary nginx.ingress.kubernetes.io/canary-weight="10" --overwrite --kubeconfig=$KUBECONFIG

  canary-50-percent:
    runs-on: ubuntu-latest
    environment:
      name: canary-50
    needs: canary-10-percent
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Kubeconfig
        run: |
          echo "${{ secrets.KUBECONFIG }}" > ./kubernetes-config

      - name: Setup kubectl
        uses: azure/setup-kubectl@v4

      - name: Set Canary to 50% Traffic
        run: |
          kubectl annotate ingress myapp-canary nginx.ingress.kubernetes.io/canary-weight="50" --overwrite --kubeconfig=$KUBECONFIG

  canary-100-percent:
    runs-on: ubuntu-latest
    environment:
      name: canary-100
    needs: canary-50-percent
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Kubeconfig
        run: |
          echo "${{ secrets.KUBECONFIG }}" > ./kubernetes-config

      - name: Setup kubectl
        uses: azure/setup-kubectl@v4

      - name: Set Canary to 100% Traffic
        run: |
          kubectl annotate ingress myapp-canary nginx.ingress.kubernetes.io/canary-weight="100" --overwrite --kubeconfig=$KUBECONFIG

  finalize-deployment:
    runs-on: ubuntu-latest
    needs: canary-100-percent
    environment: production
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Kubeconfig
        run: |
          echo "${{ secrets.KUBECONFIG }}" > ./kubernetes-config

      - name: Setup kubectl
        uses: azure/setup-kubectl@v4

      - name: Complete Deployment by removing previous deployment
        run: |
          kubectl delete -f deployment.yml --kubeconfig=$KUBECONFIG
          kubectl delete -f ingress.yml --kubeconfig=$KUBECONFIG
          kubectl annotate ingress myapp-canary nginx.ingress.kubernetes.io/canary-
          kubectl annotate ingress myapp-canary nginx.ingress.kubernetes.io/canary-weight-
